// generated by stringer -type Type; DO NOT EDIT

package lexer

import "fmt"

const _Type_name = "EOFErrorIdentFalseNumberTrueElseForIfVarBoolIntAssignMultiplyDividePlusMinusLessLessOrEqualGreaterGreaterOrEqualEqualNotEqualNotAndOrLeftParenRightParenLeftBraceRightBrace"

var _Type_index = [...]uint8{3, 8, 13, 18, 24, 28, 32, 35, 37, 40, 44, 47, 53, 61, 67, 71, 76, 80, 91, 98, 112, 117, 125, 128, 131, 133, 142, 152, 161, 171}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)) {
		return fmt.Sprintf("Type(%d)", i)
	}
	hi := _Type_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _Type_index[i-1]
	}
	return _Type_name[lo:hi]
}
